package main.java.net.ics4u.summativechess.game.board.jframe;

import java.awt.*;
import java.awt.Component;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author liame
 */
public class BoardFrame extends javax.swing.JFrame {
    public static final Color LBROWN = new Color(153, 102, 0); // Declare color brown
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BoardFrame.class.getName());
    
    
    /**
     * Creates new form BoardFrame
     */
    public BoardFrame() {
        initComponents();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BoardTable = new javax.swing.JTable()
        {
            @Override

            public Component prepareRenderer (TableCellRenderer renderer, int rowIndex, int columnIndex){
                Component componenet = super.prepareRenderer(renderer, rowIndex, columnIndex);

                Object value = getModel().getValueAt(rowIndex,columnIndex);

                if(columnIndex <= 10){

                    if(value.equals("")) // no space
                    {
                        componenet.setBackground(Color.BLACK);
                        //componenet.setForeground(Color.BLACK);

                    }else if(value.equals(" ")){ // one spaces
                        componenet.setBackground(Color.WHITE);
                        //componenet.setForeground(Color.BLACK);
                    }else {
                        componenet.setBackground(LBROWN);
                        componenet.setForeground(Color.WHITE);
                    }

                }

                return componenet;
            }

        }

        ;
        jScrollPane2 = new javax.swing.JScrollPane();
        MoveListArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        CapPieces2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        CapPieaces1 = new javax.swing.JTextArea();
        ReturnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoardTable.setBackground(new java.awt.Color(153, 153, 153));
        BoardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "},
                {"8", " ", "", " ", "", " ", "", " ", "", "   "},
                {"7", "", " ", "", " ", "", " ", "", " ", "   "},
                {"6", " ", "", " ", "", " ", "", " ", "", "   "},
                {"5", "", " ", "", " ", "", " ", "", " ", "   "},
                {"4", " ", "", " ", "", " ", "", " ", "", "   "},
                {"3", "", " ", "", " ", "", " ", "", " ", "   "},
                {"2", " ", "", " ", "", " ", "", " ", "", "   "},
                {"1", "", " ", "", " ", "", " ", "", " ", "   "},
                {"   ", "a", "b", "c", "d", "e", "f", "g", "h", "   "}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BoardTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoardTable.setGridColor(new java.awt.Color(102, 102, 102));
        BoardTable.setName(""); // NOI18N
        BoardTable.setRowHeight(55);
        BoardTable.setRowSelectionAllowed(false);
        BoardTable.setSelectionForeground(new java.awt.Color(153, 153, 153));
        BoardTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BoardTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BoardTable.setShowGrid(true);
        BoardTable.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(BoardTable);
        BoardTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (BoardTable.getColumnModel().getColumnCount() > 0) {
            BoardTable.getColumnModel().getColumn(0).setResizable(false);
            BoardTable.getColumnModel().getColumn(1).setResizable(false);
            BoardTable.getColumnModel().getColumn(2).setResizable(false);
            BoardTable.getColumnModel().getColumn(3).setResizable(false);
            BoardTable.getColumnModel().getColumn(4).setResizable(false);
            BoardTable.getColumnModel().getColumn(5).setResizable(false);
            BoardTable.getColumnModel().getColumn(6).setResizable(false);
            BoardTable.getColumnModel().getColumn(7).setResizable(false);
            BoardTable.getColumnModel().getColumn(8).setResizable(false);
            BoardTable.getColumnModel().getColumn(9).setResizable(false);
        }
        BoardTable.getAccessibleContext().setAccessibleName("");
        BoardTable.getAccessibleContext().setAccessibleDescription("");

        MoveListArea.setColumns(20);
        MoveListArea.setRows(5);
        jScrollPane2.setViewportView(MoveListArea);

        CapPieces2.setColumns(20);
        CapPieces2.setRows(5);
        CapPieces2.setText("Units captured go here. EX:\" K: 2, Q: 1, P: 5 \"");
        jScrollPane3.setViewportView(CapPieces2);

        CapPieaces1.setColumns(20);
        CapPieaces1.setRows(5);
        CapPieaces1.setText("Units captured go here. EX:\" K: 2, Q: 1, P: 5 \"");
        jScrollPane4.setViewportView(CapPieaces1);

        ReturnButton.setText("Quit");
        ReturnButton.addActionListener(this::ReturnButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BoardFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTable BoardTable;
    private javax.swing.JTextArea CapPieaces1;
    private javax.swing.JTextArea CapPieces2;
    private javax.swing.JTextArea MoveListArea;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
