/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main.java.net.ics4u.summativechess.game.board.jframe;

import main.java.net.ics4u.summativechess.game.pieces.base.Bishop;
import main.java.net.ics4u.summativechess.game.pieces.base.Knight;
import main.java.net.ics4u.summativechess.game.pieces.base.Pawn;
import main.java.net.ics4u.summativechess.game.pieces.base.Piece;
import main.java.net.ics4u.summativechess.game.pieces.base.Queen;
import main.java.net.ics4u.summativechess.game.pieces.base.Rook;

/**
 *
 * @author joshu
 */
public class PromotePopup extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PromotePopup.class.getName());

    public Pawn piece;
    
    /**
     * Creates new form PromotePopup
     */
    public PromotePopup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        queenButton.addActionListener(e -> {
            // Set the piece to be a queen
            piece.set(new Queen(piece.position, piece.player));
            
            // Make this UI no longer visible
            setVisible(false);
            
            // Delete this UI
            dispose();
        });
        bishopButton.addActionListener(e -> {
            // Set the piece to be a bishop
            piece.set(new Bishop(piece.position, piece.player));
            
            // Make this UI no longer visible
            setVisible(false);
            
            // Delete this UI
            dispose();
        });
        rookButton.addActionListener(e -> {
            // Set the piece to be a rook
            piece.set(new Rook(piece.position, piece.player));
            
            // Make this UI no longer visible
            setVisible(false);
            
            // Delete this UI
            dispose();
        });
        knightButton.addActionListener(e -> {
            // Set the piece to be a Knight
            piece.set(new Knight(piece.position, piece.player));
            
            // Make this UI no longer visible
            setVisible(false);
            
            // Delete this UI
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queenButton = new javax.swing.JButton();
        rookButton = new javax.swing.JButton();
        bishopButton = new javax.swing.JButton();
        knightButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        queenButton.setText("Queen");

        rookButton.setText("Rook");

        bishopButton.setText("Bishop");

        knightButton.setText("Knight");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Promote Your Piece!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(queenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rookButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bishopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(knightButton)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queenButton)
                    .addComponent(rookButton)
                    .addComponent(bishopButton)
                    .addComponent(knightButton))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PromotePopup dialog = new PromotePopup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bishopButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton knightButton;
    private javax.swing.JButton queenButton;
    private javax.swing.JButton rookButton;
    // End of variables declaration//GEN-END:variables
}
